version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

# Github: https://github.com/juank20097/chatbot_appointment   ///   docker build -t chatbot_appointment:latest . 
  chatbot-appointment:
    image: chatbot_appointment
    container_name: chatbot-appointment
    depends_on:
      postgres:
        condition: service_healthy
      ws-permission-back:
        condition: service_started
    ports:
      - "3000:3000"
    restart: always  
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=root
      - POSTGRES_DB_NAME=chatbot_appointment
      - POSTGRES_DB_PORT=5432

      # Información de la Empresa
      - ORG=Personal
      - LOC=IESS
      - startTime=8:00
      - endTime=17:00
      - duration=1:00
      - lunchTimeStart=13:00
      - lunchTimeEnd=14:00
      - SaturdayWork=false
      - SundayWork=false
      - OtherEvent=false
      - NumberEvents=1
      - BlackList=["01/01/2024", "12/02/2024", "13/02/2024", "29/03/2024", "01/05/2024", "24/05/2024", "10/08/2024", "09/10/2024", "02/11/2024", "03/11/2024", "25/12/2024"]

volumes:
  db:
    driver: local
